# used for local development and testing
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cypress
      MYSQL_USER: cypress
      MYSQL_PASSWORD: cypress
    volumes:
      - ./private/db:/var/lib/mysql
    ports:
      - "3306:3306"