# used for local development and testing
version: '3.8'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cypress
      MYSQL_USER: cypress
      MYSQL_PASSWORD: cypress
    volumes:
      - ./private/db:/var/lib/mysql
    ports:
      - "3306:3306"