name: Run cypress tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - working-directory: .
        run: npm i
      - working-directory: .
        run: npm run build
      - name: Run tests
        run: |
          cd test
          npm i
          npm run test
