name: Run cypress tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v5

      - name: setup node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: setup mysql 8.4
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.4"
          root-password: root
          user: cypress
          password: cypress
          my-cnf: |
            innodb_log_file_size=256MB
            innodb_buffer_pool_size=512MB
            max_allowed_packet=16MB
            max_connections=50
            local_infile=1

      - name: create cypress db
        run: |
          mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS cypress;'

      - name: run tests
        run: |
          npm i
          npm run build
          cd test
          npm i
          npm run test
